# ❤️ Heart Disease Prediction using Machine Learning

## Notebook 01 : Data Understanding

### Objective

The objective of this notebook is to understand the dataset before performing any preprocessing or model building.

### Tasks

- Import Required Libraries
- Load Dataset
- Understand Dataset Structure
- Display Sample Records
- Check Dataset Shape
- Explore Data Types
- Understand Features
- Statistical Summary
- Missing Values
- Duplicate Records
- Initial Observations

> Note:
> This notebook focuses only on understanding the dataset.

In [2]:
# ==========================================
# Import Required Libraries
# ==========================================

import pandas as pd
import numpy as np

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

print("Libraries Imported Successfully ✅")

Libraries Imported Successfully ✅

In [3]:
# ==========================================
# Load Dataset
# ==========================================

df = pd.read_csv("heart.csv")

print("Dataset Loaded Successfully ✅")

Dataset Loaded Successfully ✅

In [4]:
# ==========================================
# Display Dataset
# ==========================================

print("First 5 Records")
display(df.head())

print("\nLast 5 Records")
display(df.tail())

First 5 Records

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

Last 5 Records

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [5]:
# ==========================================
# Dataset Shape
# ==========================================

rows, columns = df.shape

print(f"Number of Rows    : {rows}")
print(f"Number of Columns : {columns}")

Number of Rows    : 918
Number of Columns : 12

In [6]:
# ==========================================
# Column Names
# ==========================================

print("Dataset Columns\n")

for column in df.columns:
    print(column)

Dataset Columns

Age
Sex
ChestPainType
RestingBP
Cholesterol
FastingBS
RestingECG
MaxHR
ExerciseAngina
Oldpeak
ST_Slope
HeartDisease

In [7]:
# ==========================================
# Dataset Information
# ==========================================

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 86.2 KB

In [8]:
# ==========================================
# Statistical Summary
# ==========================================

df.describe().T

              count        mean         std   min     25%    50%    75%    max
Age           918.0   53.510893    9.432617  28.0   47.00   54.0   60.0   77.0
RestingBP     918.0  132.396514   18.514154   0.0  120.00  130.0  140.0  200.0
Cholesterol   918.0  198.799564  109.384145   0.0  173.25  223.0  267.0  603.0
FastingBS     918.0    0.233115    0.423046   0.0    0.00    0.0    0.0    1.0
MaxHR         918.0  136.809368   25.460334  60.0  120.00  138.0  156.0  202.0
Oldpeak       918.0    0.887364    1.066570  -2.6    0.00    0.6    1.5    6.2
HeartDisease  918.0    0.553377    0.497414   0.0    0.00    1.0    1.0    1.0

In [9]:
# ==========================================
# Categorical Summary
# ==========================================

df.describe(include="object").T

C:\Users\Mohit Goswami\AppData\Local\Temp\ipykernel_26896\480311256.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object").T

               count unique     top freq
Sex              918      2       M  725
ChestPainType    918      4     ASY  496
RestingECG       918      3  Normal  552
ExerciseAngina   918      2       N  547
ST_Slope         918      3    Flat  460

In [10]:
# ==========================================
# Missing Values
# ==========================================

missing_values = df.isnull().sum()

missing_values

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [11]:
# ==========================================
# Duplicate Records
# ==========================================

duplicate_count = df.duplicated().sum()

print("Duplicate Records :", duplicate_count)

Duplicate Records : 0

In [12]:
# ==========================================
# Unique Values
# ==========================================

df.nunique().sort_values()

Sex                 2
FastingBS           2
HeartDisease        2
ExerciseAngina      2
RestingECG          3
ST_Slope            3
ChestPainType       4
Age                50
Oldpeak            53
RestingBP          67
MaxHR             119
Cholesterol       222
dtype: int64

In [13]:
# ==========================================
# Target Variable
# ==========================================

df["HeartDisease"].value_counts()

HeartDisease
1    508
0    410
Name: count, dtype: int64

In [14]:
# ==========================================
# Target Percentage
# ==========================================

(
    df["HeartDisease"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

HeartDisease
1    55.34
0    44.66
Name: proportion, dtype: float64

In [15]:
feature_description = pd.DataFrame({
    "Feature": df.columns,
    "Data Type": df.dtypes.values
})

feature_description

           Feature Data Type
0              Age     int64
1              Sex       str
2    ChestPainType       str
3        RestingBP     int64
4      Cholesterol     int64
5        FastingBS     int64
6       RestingECG       str
7            MaxHR     int64
8   ExerciseAngina       str
9          Oldpeak   float64
10        ST_Slope       str
11    HeartDisease     int64

In [16]:
print("="*60)

print("Notebook 01 Completed Successfully")

print("="*60)

print(f"Total Rows      : {rows}")
print(f"Total Columns   : {columns}")
print(f"Duplicate Rows  : {duplicate_count}")
print(f"Missing Values  : {df.isnull().sum().sum()}")

print("="*60)

============================================================
Notebook 01 Completed Successfully
============================================================
Total Rows      : 918
Total Columns   : 12
Duplicate Rows  : 0
Missing Values  : 0
============================================================