# ❤️ Heart Disease Prediction using Machine Learning

# Notebook 03 : Data Preprocessing

## Objective

This notebook prepares the dataset for machine learning.

### Tasks

- Missing Value Analysis
- Duplicate Check
- Feature Encoding
- Feature Scaling
- Train-Test Split

> Note:
> No model will be trained in this notebook.

In [1]:
# =====================================
# Import Required Libraries
# =====================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

print("Libraries Imported Successfully ✅")

Libraries Imported Successfully ✅

In [2]:
# =====================================
# Load Dataset
# =====================================

df = pd.read_csv("heart.csv")

df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 86.2 KB

In [4]:
missing_values = df.isnull().sum()

print("Missing Values")

missing_values

Missing Values

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [5]:
duplicate_rows = df.duplicated().sum()

print("Duplicate Rows :", duplicate_rows)

Duplicate Rows : 0

In [6]:
df = df.drop_duplicates()

print("New Shape :", df.shape)

New Shape : (918, 12)

In [7]:
X = df.drop("HeartDisease", axis=1)

y = df["HeartDisease"]

print("Features Shape :", X.shape)

print("Target Shape :", y.shape)

Features Shape : (918, 11)
Target Shape : (918,)

In [8]:
categorical_columns = X.select_dtypes(include="object").columns

categorical_columns

C:\Users\Mohit Goswami\AppData\Local\Temp\ipykernel_24348\3696774006.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(include="object").columns

Index(['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'], dtype='str')

In [9]:
X = pd.get_dummies(

    X,

    columns=categorical_columns,

    drop_first=True

)

X.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,True,False,True,False,True,False,False,False,True

In [10]:
print("Encoded Feature Shape :", X.shape)

Encoded Feature Shape : (918, 15)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)

print("Training Samples :", X_train.shape)

print("Testing Samples :", X_test.shape)

Training Samples : (734, 15)
Testing Samples : (184, 15)

In [12]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

print("Scaling Completed Successfully ✅")

Scaling Completed Successfully ✅

In [13]:
X_train_scaled = pd.DataFrame(

    X_train_scaled,

    columns=X_train.columns

)

X_test_scaled = pd.DataFrame(

    X_test_scaled,

    columns=X_test.columns

)

In [14]:
X_train_scaled.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,0.970012,0.339016,0.127137,1.835497,-0.324520,0.317046,0.51740,2.096917,-0.5174,-0.240077,-1.247995,2.050774,1.202775,0.981105,-0.862246
1,0.122028,-1.266031,0.099443,1.835497,1.689837,-0.440356,0.51740,2.096917,-0.5174,-0.240077,-1.247995,2.050774,-0.831411,-1.019259,1.159762
2,0.546020,-0.159102,1.244113,1.835497,-0.247045,0.601071,-1.93274,-0.476891,-0.5174,-0.240077,-1.247995,2.050774,1.202775,0.981105,-0.862246
3,-0.725956,1.501291,-1.876035,-0.544812,-0.479470,-0.819056,0.51740,-0.476891,-0.5174,-0.240077,0.801285,-0.487621,1.202775,0.981105,-0.862246
4,-0.407962,0.671094,-1.876035,1.835497,0.101594,-0.156330,0.51740,-0.476891,-0.5174,-0.240077,0.801285,-0.487621,1.202775,0.981105,-0.862246

In [15]:
print("="*60)

print("Data Preprocessing Completed Successfully")

print("="*60)

print("Original Dataset :", df.shape)

print("Training Set :", X_train_scaled.shape)

print("Testing Set :", X_test_scaled.shape)

print("="*60)

============================================================
Data Preprocessing Completed Successfully
============================================================
Original Dataset : (918, 12)
Training Set : (734, 15)
Testing Set : (184, 15)
============================================================

In [16]:
print("="*60)

print("Data Preprocessing Completed Successfully")

print("="*60)

print("Original Dataset :", df.shape)

print("Training Set :", X_train_scaled.shape)

print("Testing Set :", X_test_scaled.shape)

print("="*60)

============================================================
Data Preprocessing Completed Successfully
============================================================
Original Dataset : (918, 12)
Training Set : (734, 15)
Testing Set : (184, 15)
============================================================